package app.pulse.android.mirror

/**
 * R66 - the 100-platform Apps Matrix, ported VERBATIM from the web's
 * src/lib/hub-catalog.ts (the static catalog the Hub > Apps panel renders).
 * Same 10 categories, same nav styles, same input/secret copy - the mirror
 * renders the exact data the browser renders.
 */
internal data class MatrixApp(
    val n: Int,
    val name: String,
    val nav: String,
    val input: String,
    val category: String,
    val secret: String,
)

internal object HubCatalog {

    val CATEGORY_CHIPS: List<Pair<String, String>> = listOf(
        "all" to "All",
        "Web3 FinTech / Hyper-Apps" to "Web3",
        "Dev-Ops / Community Boards" to "Dev-Ops",
        "Workplace Canvas / Dev-Ops" to "Workplace",
        "E-Commerce Showcase" to "E-Commerce",
        "Stark Privacy Minimalist" to "Privacy",
        "Cross-Server Bridges / Matrix" to "Bridges",
        "Spatial 3D Environments" to "Spatial 3D",
        "Spatial 2D/3D Art" to "Spatial 2D",
    )

    /** Extra chips for categories the static chip list misses (web EXTRA_CHIP_LABELS). */
    fun extraChipLabel(category: String): String? = when (category) {
        "E-Commerce / Global FinTech" -> "Global FinTech"
        "E-Commerce / Hyper-Apps" -> "Hyper-Apps"
        else -> null
    }

    val MATRIX: List<MatrixApp> = listOf(
        MatrixApp(1, "Discord", "Persistent Solid Split Rail", "Media slider, rich presence triggers", "Dev-Ops / Community Boards", "WebGL custom profile mesh themes"),
        MatrixApp(2, "Slack", "Persistent Solid Split Rail", "Lightning bolt workflow automation picker", "Workplace Canvas / Dev-Ops", "Slide-out right-side thread panels"),
        MatrixApp(3, "WhatsApp", "Floating Acrylic Bottom Dock", "Cubic-bezier + media sheet, voice seek", "E-Commerce / Global FinTech", "Real-time audio canvas waveforms"),
        MatrixApp(4, "Telegram", "Floating Acrylic Bottom Dock", "Paperclip sheet, mini-app launcher button", "Web3 FinTech / Hyper-Apps", "Real-time Gaussian blur overlay headers"),
        MatrixApp(5, "Signal", "Persistent Solid Split Rail", "Disappearing text timer wheel indicator", "Stark Privacy Minimalist", "Localized pin database security shields"),
        MatrixApp(6, "Element", "Floating Acrylic Bottom Dock", "Cross-signing cryptographic check toggle", "Cross-Server Bridges / Matrix", "Dynamic server origin labels on text blocks"),
        MatrixApp(7, "Revolt", "Minimalist Hidden Edge Rail", "Markdown auto-syntax triggers, raw code blocks", "Dev-Ops / Community Boards", "High-density text layout configuration panels"),
        MatrixApp(8, "Beeper", "Floating Acrylic Bottom Dock", "Unified network protocol adapter badge", "Cross-Server Bridges / Matrix", "Sub-icon branding indicators on contact avatars"),
        MatrixApp(9, "Threema", "Persistent Solid Split Rail", "Anonymous encrypted inline polling sheets", "Stark Privacy Minimalist", "Random alphanumeric user ID generator screens"),
        MatrixApp(10, "Viber", "Floating Acrylic Bottom Dock", "Interactive shopping / GIF carousels", "E-Commerce Showcase", "Hidden text vault secure PIN keypad sheets"),
        MatrixApp(11, "WeChat", "Persistent Solid Split Rail", "Invoice tracking / red packet cash triggers", "E-Commerce / Global FinTech", "Pull-down recently used mini-app drawer layer"),
        MatrixApp(12, "LINE", "Persistent Solid Split Rail", "Character sticker shop canvas engine", "E-Commerce Showcase", "Dynamic message expansions for large graphics"),
        MatrixApp(13, "KakaoTalk", "Persistent Solid Split Rail", "Shared group calendar reservation picker", "E-Commerce Showcase", "Rounded card grid gift marketplace views"),
        MatrixApp(14, "Session", "Minimalist Hidden Edge Rail", "Multi-hop onion routing telemetry indicator", "Stark Privacy Minimalist", "Alphanumeric account key security containers"),
        MatrixApp(15, "Wickr", "Persistent Solid Split Rail", "Hardware-level shredder timer count blocks", "Stark Privacy Minimalist", "Local device cache deletion admin panels"),
        MatrixApp(16, "Matrix", "Minimalist Hidden Edge Rail", "Raw JSON payload inspector triggers", "Cross-Server Bridges / Matrix", "Open-source multi-server directory indices"),
        MatrixApp(17, "Twitch", "Persistent Solid Split Rail", "Micro-transaction cheers, sub badges", "Dev-Ops / Community Boards", "Stream canvas panel fixed layout parameters"),
        MatrixApp(18, "Microsoft Teams", "Persistent Solid Split Rail", "Font hierarchy rail, message importance toggle", "Workplace Canvas / Dev-Ops", "Acrylic blur panel real-time live captions"),
        MatrixApp(19, "Google Chat", "Persistent Solid Split Rail", "Context-aware AI text chip trays", "Workplace Canvas / Dev-Ops", "Side-panel document collaboration viewers"),
        MatrixApp(20, "Zoom", "Persistent Solid Split Rail", "Drawing canvas whiteboard launching toggle", "Workplace Canvas / Dev-Ops", "Vector ink line whiteboard workspaces"),
        MatrixApp(21, "Webex", "Persistent Solid Split Rail", "AI background noise-tuning level meters", "Workplace Canvas / Dev-Ops", "Decibel suppression telemetry dashboards"),
        MatrixApp(22, "Chanty", "Floating Acrylic Bottom Dock", "Direct kanban task conversion actions", "Workplace Canvas / Dev-Ops", "Interactive drag-and-drop workflow sheets"),
        MatrixApp(23, "Flock", "Persistent Solid Split Rail", "Integrated collaborative checklist modules", "Workplace Canvas / Dev-Ops", "Three-pane desktop split layout structure"),
        MatrixApp(24, "Ryver", "Persistent Solid Split Rail", "Split-screen kanban task generators", "Workplace Canvas / Dev-Ops", "Bulletin forum board corporate layouts"),
        MatrixApp(25, "Mattermost", "Minimalist Hidden Edge Rail", "Operational deployment playbook connectors", "Dev-Ops / Community Boards", "Incident emergency response logging streams"),
        MatrixApp(26, "Rocket.Chat", "Minimalist Hidden Edge Rail", "Multi-channel outgoing language translators", "Workplace Canvas / Dev-Ops", "Multi-source ticket sorting inbox tables"),
        MatrixApp(27, "Zulip", "Minimalist Hidden Edge Rail", "Mandatory topic title composition fields", "Workplace Canvas / Dev-Ops", "Explicit conversation category top banners"),
        MatrixApp(28, "Fumble", "Persistent Solid Split Rail", "Live git code repository link pickers", "Dev-Ops / Community Boards", "Language color badge repository indicators"),
        MatrixApp(29, "Guilded", "Persistent Solid Split Rail", "Shared tournament bracket calendar loaders", "Dev-Ops / Community Boards", "Zoomable HTML5 gaming bracket layouts"),
        MatrixApp(30, "TeamSpeak", "Minimalist Hidden Edge Rail", "Push-to-talk key mapping matrices", "Dev-Ops / Community Boards", "Hierarchical server structural connection trees"),
        MatrixApp(31, "Mumble", "Minimalist Hidden Edge Rail", "Low-latency audio voice threshold sliders", "Dev-Ops / Community Boards", "Directional 3D acoustic layout tuners"),
        MatrixApp(32, "Steam Chat", "Floating Acrylic Bottom Dock", "PC hardware monitoring lookup readouts", "Dev-Ops / Community Boards", "Direct game invite pop-up sliding panels"),
        MatrixApp(33, "Skype", "Persistent Solid Split Rail", "Cellular landline destination dialers", "Workplace Canvas / Dev-Ops", "Translucent blurred background video filters"),
        MatrixApp(34, "VRChat", "Volumetric Radial Overlay", "3D avatar facial expression dials", "Spatial 3D Environments", "Floating virtual controller attachment panes"),
        MatrixApp(35, "Rec Room", "Volumetric Radial Overlay", "Visual programming logic node wire frames", "Spatial 3D Environments", "Volumetric wearable watch control screens"),
        MatrixApp(36, "Snapchat", "Volumetric Radial Overlay", "Fullscreen camera AR lens asset triggers", "Spatial 3D Environments", "Full-bleed vector cartographic friend maps"),
        MatrixApp(37, "Instagram DM", "Floating Acrylic Bottom Dock", "Inline video post looping components", "E-Commerce Showcase", "Gradient mesh chat background customization"),
        MatrixApp(38, "TikTok Inbox", "Persistent Solid Split Rail", "Trending audio clip clip samplers", "E-Commerce Showcase", "Swipe-to-reply video response capture frames"),
        MatrixApp(39, "X DMs", "Persistent Solid Split Rail", "Secure audio call network routers", "Stark Privacy Minimalist", "Audio space round profile indicator borders"),
        MatrixApp(40, "Threads", "Persistent Solid Split Rail", "Text-first thread branching lane links", "Workplace Canvas / Dev-Ops", "Branching timeline connection lines"),
        MatrixApp(41, "iMessage", "Persistent Solid Split Rail", "Physics-based text effect button engines", "Spatial 2D/3D Art", "Fullscreen screen-space particle loops"),
        MatrixApp(42, "Google Messages", "Persistent Solid Split Rail", "RCS connection status validation meters", "E-Commerce Showcase", "Dynamic system-matching theme palette layouts"),
        MatrixApp(43, "RCS Chat", "Persistent Solid Split Rail", "Verified commercial account badge queries", "E-Commerce Showcase", "Carrier-level video container components"),
        MatrixApp(44, "Voxer", "Volumetric Radial Overlay", "Oversized touch push-to-talk buttons", "Spatial 2D/3D Art", "Real-time scrolling voice note meters"),
        MatrixApp(45, "Zello", "Volumetric Radial Overlay", "Field dispatch channel isolation knobs", "Workplace Canvas / Dev-Ops", "Bright red crisis emergency broadcast screens"),
        MatrixApp(46, "Marco Polo", "Floating Acrylic Bottom Dock", "Asynchronous video note capture wheels", "Spatial 2D/3D Art", "Chronological friend video diary grids"),
        MatrixApp(47, "Clubhouse", "Floating Acrylic Bottom Dock", "Virtual panel hand-raise request icons", "Spatial 2D/3D Art", "Stage speaker card alignment grids"),
        MatrixApp(48, "Twitter Spaces", "Floating Acrylic Bottom Dock", "Audio transcription captioning toggles", "Spatial 2D/3D Art", "Dynamic talker border glow visual layers"),
        MatrixApp(49, "BeReal", "Volumetric Radial Overlay", "Dual-camera matrix sensor triggers", "Spatial 2D/3D Art", "Picture-in-picture selfie realmoji sheets"),
        MatrixApp(50, "Bere.al", "Volumetric Radial Overlay", "Timeline submission clock confirmations", "Spatial 2D/3D Art", "Flat high-contrast text timeline blocks"),
        MatrixApp(51, "Status", "Floating Acrylic Bottom Dock", "Ethereum contract transaction bars", "Web3 FinTech / Hyper-Apps", "Monospace asset ledger financial graphs"),
        MatrixApp(52, "Status IM", "Floating Acrylic Bottom Dock", "Decentralized ID verification blocks", "Web3 FinTech / Hyper-Apps", "Biometric fingerprint security splash panels"),
        MatrixApp(53, "Status Network", "Minimalist Hidden Edge Rail", "Cross-app data distribution permission chips", "Web3 FinTech / Hyper-Apps", "Public identity cryptographic key profiles"),
        MatrixApp(54, "Session Messaging", "Minimalist Hidden Edge Rail", "Onion-routing transmission hop log metrics", "Stark Privacy Minimalist", "Secure local database data storage panels"),
        MatrixApp(55, "SimpleX Chat", "Minimalist Hidden Edge Rail", "Unidirectional invitation key builders", "Stark Privacy Minimalist", "High-contrast temporary invite QR views"),
        MatrixApp(56, "Briar", "Minimalist Hidden Edge Rail", "Bluetooth mesh connection discovery lookups", "Stark Privacy Minimalist", "Local device proximity hardware charts"),
        MatrixApp(57, "Jami", "Minimalist Hidden Edge Rail", "Distributed Hash Table diagnostic maps", "Spatial 2D/3D Art", "Full-bleed direct peer-to-peer call lanes"),
        MatrixApp(58, "Tox", "Minimalist Hidden Edge Rail", "P2P un-throttled speed calculation panels", "Stark Privacy Minimalist", "Horizontal expanding chat box layouts"),
        MatrixApp(59, "Wire", "Persistent Solid Split Rail", "Sovereign enterprise key permission toggles", "Workplace Canvas / Dev-Ops", "High-end typography corporate cloud links"),
        MatrixApp(60, "Dust", "Persistent Solid Split Rail", "Automatic screenshot detection blocks", "Stark Privacy Minimalist", "Self-shredding floating pixel animations"),
        MatrixApp(61, "Keybase", "Minimalist Hidden Edge Rail", "Git repository cryptographic signing blocks", "Dev-Ops / Community Boards", "Monospace dev identity proof verification cards"),
        MatrixApp(62, "Spike", "Floating Acrylic Bottom Dock", "Expanded conversational email row managers", "Workplace Canvas / Dev-Ops", "Stripped signature header bubble streams"),
        MatrixApp(63, "Missive", "Floating Acrylic Bottom Dock", "Real-time concurrent text creation sheets", "Workplace Canvas / Dev-Ops", "Collaborative multi-user email text editors"),
        MatrixApp(64, "Front", "Persistent Solid Split Rail", "Multi-channel customer service selectors", "Workplace Canvas / Dev-Ops", "Customer interaction metadata sidebar rows"),
        MatrixApp(65, "Intercom", "Volumetric Radial Overlay", "Automated help center knowledge base indices", "E-Commerce Showcase", "Slide-in self-service web widget overlays"),
        MatrixApp(66, "Drift", "Volumetric Radial Overlay", "Inline automated calendar setting popups", "E-Commerce Showcase", "Oversized lead collection call-to-action cards"),
        MatrixApp(67, "Crisp", "Volumetric Radial Overlay", "Live agent cursor tracker controllers", "E-Commerce Showcase", "WebGL real-time visitor coordinate maps"),
        MatrixApp(68, "Tidio", "Volumetric Radial Overlay", "Shopify database cart lookup drawers", "E-Commerce Showcase", "Drag-and-drop response automation node loops"),
        MatrixApp(69, "Zendesk Chat", "Persistent Solid Split Rail", "Macro response script shortcut templates", "Workplace Canvas / Dev-Ops", "Browser-style agent multi-user window tabs"),
        MatrixApp(70, "HubSpot Chat", "Persistent Solid Split Rail", "CRM interaction history timeline lookups", "E-Commerce Showcase", "Integrated enterprise deal stage pipelines"),
        MatrixApp(71, "ManyChat", "Minimalist Hidden Edge Rail", "Social ad automated lead funnel markers", "E-Commerce Showcase", "Zoomable customer path logic canvases"),
        MatrixApp(72, "Chatfuel", "Minimalist Hidden Edge Rail", "Meta network chat configuration option items", "E-Commerce Showcase", "Horizontal reply carousel product menus"),
        MatrixApp(73, "MobileMonkey", "Minimalist Hidden Edge Rail", "Ad campaign source routing parameters", "E-Commerce Showcase", "Inbound marketing audience segment matrices"),
        MatrixApp(74, "Landbot", "Volumetric Radial Overlay", "Fullscreen media item choice chips", "Spatial 2D/3D Art", "Full-bleed interactive background canvases"),
        MatrixApp(75, "Tars", "Volumetric Radial Overlay", "Mobile thumb-optimized form data fields", "E-Commerce Showcase", "High-contrast single-track marketing tunnels"),
        MatrixApp(76, "Typeform Chat", "Volumetric Radial Overlay", "Question-by-question layout transitions", "Spatial 2D/3D Art", "Minimalist survey option selection paths"),
        MatrixApp(77, "Jostle", "Floating Acrylic Bottom Dock", "Internal update thread posting shortcuts", "Workplace Canvas / Dev-Ops", "Magazine-style milestone photo layout blocks"),
        MatrixApp(78, "Workplace", "Persistent Solid Split Rail", "Corporate live stream feedback reactions", "Workplace Canvas / Dev-Ops", "Policy document storage knowledge libraries"),
        MatrixApp(79, "Basecamp Chat", "Persistent Solid Split Rail", "Context-focused milestone mention checkers", "Workplace Canvas / Dev-Ops", "Campfire conversation text row containers"),
        MatrixApp(80, "ClickUp Chat", "Persistent Solid Split Rail", "Agile workspace sprint link managers", "Workplace Canvas / Dev-Ops", "Real-time wiki document editor lanes"),
        MatrixApp(81, "Asana Chat", "Persistent Solid Split Rail", "Direct task dependency status verifiers", "Workplace Canvas / Dev-Ops", "High-resolution project Gantt timeline charts"),
        MatrixApp(82, "Monday Chat", "Persistent Solid Split Rail", "Status column automated update hooks", "Workplace Canvas / Dev-Ops", "Slide-out database row update panels"),
        MatrixApp(83, "Notion Chat", "Minimalist Hidden Edge Rail", "Inline block-anchored discussion threads", "Workplace Canvas / Dev-Ops", "High-whitespace page modification ledgers"),
        MatrixApp(84, "Miro Chat", "Minimalist Hidden Edge Rail", "Whiteboard team canvas focus selectors", "Spatial 2D/3D Art", "Real-time cursor particle text labels"),
        MatrixApp(85, "Figma Chat", "Minimalist Hidden Edge Rail", "Cursor tracking vector feedback launchers", "Spatial 2D/3D Art", "Floating viewport design comment sidebars"),
        MatrixApp(86, "Gather.town", "Volumetric Radial Overlay", "Local proximity range layout rules", "Spatial 3D Environments", "16-bit pixel landscape private room maps"),
        MatrixApp(87, "Kumospace", "Volumetric Radial Overlay", "Spatial broadcast perimeter distance bars", "Spatial 3D Environments", "Floor plan WebGL presentation templates"),
        MatrixApp(88, "Topia", "Volumetric Radial Overlay", "Hand-sketched link insertion parameters", "Spatial 3D Environments", "Fading circular participant video bubbles"),
        MatrixApp(89, "Spatial", "Volumetric Radial Overlay", "Digital wallet gallery verification tools", "Spatial 3D Environments", "3D museum display room asset frameworks"),
        MatrixApp(90, "Roblox Chat", "Volumetric Radial Overlay", "Real-time text safety filter scanners", "Spatial 3D Environments", "Translucent in-game game canvas boxes"),
        MatrixApp(91, "Minecraft Chat", "Volumetric Radial Overlay", "Server console command execution sheets", "Spatial 3D Environments", "Monospace script auto-complete panels"),
        MatrixApp(92, "Among Us Chat", "Volumetric Radial Overlay", "Round-timer selection shortcut matrices", "Spatial 3D Environments", "Character target voting card layouts"),
        MatrixApp(93, "Plato", "Floating Acrylic Bottom Dock", "Casual turn-based board game match sheets", "Dev-Ops / Community Boards", "Split-pane chat / multiplayer arcade frames"),
        MatrixApp(94, "Hago", "Floating Acrylic Bottom Dock", "3D screen animation gift trigger boxes", "Dev-Ops / Community Boards", "Horizontal interactive virtual store rails"),
        MatrixApp(95, "Yubo", "Floating Acrylic Bottom Dock", "Swiping category preference filters", "Spatial 2D/3D Art", "Equal-tiled camera grid layout boxes"),
        MatrixApp(96, "Leket", "Persistent Solid Split Rail", "Food delivery drop-off tracking maps", "Workplace Canvas / Dev-Ops", "Local civic volunteer routing indicators"),
        MatrixApp(97, "Amino", "Persistent Solid Split Rail", "Fan wiki resource authoring toolsets", "Dev-Ops / Community Boards", "Custom fandom color theme asset builders"),
        MatrixApp(98, "Band", "Persistent Solid Split Rail", "Team attendance roster check-in blocks", "Workplace Canvas / Dev-Ops", "Roster item balance configuration matrices"),
        MatrixApp(99, "MeWe", "Persistent Solid Split Rail", "Non-tracking data privacy switch controls", "Stark Privacy Minimalist", "Chronological ad-free personal social feeds"),
        MatrixApp(100, "Nextdoor", "Persistent Solid Split Rail", "Verified address localized proximity grids", "Spatial 3D Environments", "Amber safety notice alert container plates"),
    )
}
