
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  username: 'username',
  about: 'about',
  color: 'color',
  avatar: 'avatar',
  statusEmoji: 'statusEmoji',
  statusText: 'statusText',
  preferences: 'preferences',
  createdAt: 'createdAt',
  lastSeenAt: 'lastSeenAt',
  xp: 'xp',
  xpToday: 'xpToday',
  xpDay: 'xpDay'
};

exports.Prisma.ReminderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  messageId: 'messageId',
  note: 'note',
  remindAt: 'remindAt',
  firedAt: 'firedAt',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationStreakScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  userId: 'userId',
  lastDay: 'lastDay',
  count: 'count',
  best: 'best'
};

exports.Prisma.CallLogScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  callerId: 'callerId',
  calleeId: 'calleeId',
  kind: 'kind',
  status: 'status',
  durationSec: 'durationSec',
  startedAt: 'startedAt'
};

exports.Prisma.UserVerificationScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  peerId: 'peerId',
  verifiedAt: 'verifiedAt'
};

exports.Prisma.UserWalletScalarFieldEnum = {
  userId: 'userId',
  coins: 'coins',
  gems: 'gems',
  streak: 'streak',
  lastCheckIn: 'lastCheckIn'
};

exports.Prisma.WalletLedgerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kind: 'kind',
  asset: 'asset',
  amount: 'amount',
  note: 'note',
  counterpartyId: 'counterpartyId',
  createdAt: 'createdAt'
};

exports.Prisma.HubTaskScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  title: 'title',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AppInstallScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  appId: 'appId',
  installedAt: 'installedAt',
  status: 'status'
};

exports.Prisma.MarketListingScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  title: 'title',
  description: 'description',
  price: 'price',
  asset: 'asset',
  status: 'status',
  buyerId: 'buyerId',
  createdAt: 'createdAt'
};

exports.Prisma.LogEventScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kind: 'kind',
  message: 'message',
  meta: 'meta',
  createdAt: 'createdAt'
};

exports.Prisma.QuickPhraseScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  text: 'text',
  position: 'position',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  isGroup: 'isGroup',
  name: 'name',
  description: 'description',
  photo: 'photo',
  inviteCode: 'inviteCode',
  ttlSeconds: 'ttlSeconds',
  broadcastMode: 'broadcastMode',
  screenPrivacy: 'screenPrivacy',
  isSelf: 'isSelf',
  appKey: 'appKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AutomationScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  trigger: 'trigger',
  reply: 'reply',
  createdById: 'createdById',
  enabled: 'enabled',
  hits: 'hits',
  lastFiredAt: 'lastFiredAt',
  createdAt: 'createdAt'
};

exports.Prisma.WebhookScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  token: 'token',
  name: 'name',
  avatarColor: 'avatarColor',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.WhiteboardStrokeScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  userId: 'userId',
  color: 'color',
  width: 'width',
  points: 'points',
  createdAt: 'createdAt'
};

exports.Prisma.StatusStoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  imagePath: 'imagePath',
  caption: 'caption',
  background: 'background',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.StoryViewScalarFieldEnum = {
  id: 'id',
  storyId: 'storyId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationParticipantScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  role: 'role',
  joinedAt: 'joinedAt',
  lastReadAt: 'lastReadAt',
  pinnedAt: 'pinnedAt',
  mutedUntil: 'mutedUntil',
  archivedAt: 'archivedAt',
  handRaisedAt: 'handRaisedAt',
  screenPrivacy: 'screenPrivacy'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderId: 'senderId',
  content: 'content',
  deletedAt: 'deletedAt',
  replyToId: 'replyToId',
  imagePath: 'imagePath',
  audioPath: 'audioPath',
  durationMs: 'durationMs',
  filePath: 'filePath',
  fileName: 'fileName',
  fileSize: 'fileSize',
  editedAt: 'editedAt',
  pinnedAt: 'pinnedAt',
  pinnedBy: 'pinnedBy',
  parentId: 'parentId',
  topicId: 'topicId',
  anon: 'anon',
  viaAutomation: 'viaAutomation',
  transcript: 'transcript',
  transcribedAt: 'transcribedAt',
  transcribedById: 'transcribedById',
  anonAlias: 'anonAlias',
  viewOnce: 'viewOnce',
  viewedAt: 'viewedAt',
  viewedBy: 'viewedBy',
  expiresAt: 'expiresAt',
  linkUrl: 'linkUrl',
  kind: 'kind',
  payload: 'payload',
  createdAt: 'createdAt'
};

exports.Prisma.PollScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  question: 'question',
  closedAt: 'closedAt',
  createdAt: 'createdAt'
};

exports.Prisma.PollOptionScalarFieldEnum = {
  id: 'id',
  pollId: 'pollId',
  text: 'text',
  position: 'position'
};

exports.Prisma.PollVoteScalarFieldEnum = {
  id: 'id',
  pollId: 'pollId',
  optionId: 'optionId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.SavedMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  messageId: 'messageId',
  savedAt: 'savedAt'
};

exports.Prisma.ScheduledMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderId: 'senderId',
  content: 'content',
  scheduledAt: 'scheduledAt',
  sentAt: 'sentAt',
  createdAt: 'createdAt'
};

exports.Prisma.MessageTranslationScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  lang: 'lang',
  text: 'text',
  createdAt: 'createdAt'
};

exports.Prisma.LinkPreviewScalarFieldEnum = {
  url: 'url',
  title: 'title',
  description: 'description',
  imageUrl: 'imageUrl',
  siteName: 'siteName',
  fetchedAt: 'fetchedAt'
};

exports.Prisma.ReactionScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  userId: 'userId',
  emoji: 'emoji',
  createdAt: 'createdAt'
};

exports.Prisma.TopicScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  name: 'name',
  emoji: 'emoji',
  createdById: 'createdById',
  createdAt: 'createdAt',
  lastMessageAt: 'lastMessageAt'
};

exports.Prisma.FolderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  emoji: 'emoji',
  position: 'position',
  createdAt: 'createdAt'
};

exports.Prisma.FolderConversationScalarFieldEnum = {
  id: 'id',
  folderId: 'folderId',
  conversationId: 'conversationId',
  position: 'position'
};

exports.Prisma.TournamentScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  name: 'name',
  game: 'game',
  status: 'status',
  createdById: 'createdById',
  endsAt: 'endsAt',
  createdAt: 'createdAt'
};

exports.Prisma.TournamentPlayerScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  userId: 'userId',
  points: 'points',
  wins: 'wins',
  losses: 'losses',
  draws: 'draws',
  joinedAt: 'joinedAt'
};

exports.Prisma.RedPacketScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  senderId: 'senderId',
  total: 'total',
  count: 'count',
  grabbed: 'grabbed',
  slices: 'slices',
  note: 'note',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.RedPacketGrabScalarFieldEnum = {
  id: 'id',
  packetId: 'packetId',
  userId: 'userId',
  amount: 'amount',
  createdAt: 'createdAt'
};

exports.Prisma.GameMatchScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  game: 'game',
  playerXId: 'playerXId',
  playerOId: 'playerOId',
  board: 'board',
  turn: 'turn',
  status: 'status',
  winnerId: 'winnerId',
  winLine: 'winLine',
  moveCount: 'moveCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KanbanCardScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  title: 'title',
  column: 'column',
  position: 'position',
  assigneeId: 'assigneeId',
  createdById: 'createdById',
  sourceMessageId: 'sourceMessageId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GroupEventScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  title: 'title',
  description: 'description',
  location: 'location',
  startsAt: 'startsAt',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.EventRsvpScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  userId: 'userId',
  status: 'status',
  checkedInAt: 'checkedInAt',
  createdAt: 'createdAt'
};

exports.Prisma.UploadedFileScalarFieldEnum = {
  name: 'name',
  mime: 'mime',
  bytes: 'bytes',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Reminder: 'Reminder',
  ConversationStreak: 'ConversationStreak',
  CallLog: 'CallLog',
  UserVerification: 'UserVerification',
  UserWallet: 'UserWallet',
  WalletLedger: 'WalletLedger',
  HubTask: 'HubTask',
  AppInstall: 'AppInstall',
  MarketListing: 'MarketListing',
  LogEvent: 'LogEvent',
  QuickPhrase: 'QuickPhrase',
  Conversation: 'Conversation',
  Automation: 'Automation',
  Webhook: 'Webhook',
  WhiteboardStroke: 'WhiteboardStroke',
  StatusStory: 'StatusStory',
  StoryView: 'StoryView',
  ConversationParticipant: 'ConversationParticipant',
  Message: 'Message',
  Poll: 'Poll',
  PollOption: 'PollOption',
  PollVote: 'PollVote',
  SavedMessage: 'SavedMessage',
  ScheduledMessage: 'ScheduledMessage',
  MessageTranslation: 'MessageTranslation',
  LinkPreview: 'LinkPreview',
  Reaction: 'Reaction',
  Topic: 'Topic',
  Folder: 'Folder',
  FolderConversation: 'FolderConversation',
  Tournament: 'Tournament',
  TournamentPlayer: 'TournamentPlayer',
  RedPacket: 'RedPacket',
  RedPacketGrab: 'RedPacketGrab',
  GameMatch: 'GameMatch',
  KanbanCard: 'KanbanCard',
  GroupEvent: 'GroupEvent',
  EventRsvp: 'EventRsvp',
  UploadedFile: 'UploadedFile'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
